# Generated by Django 5.2 on 2025-05-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_estudiante_slug_estudiante_user_alter_curso_camada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
        migrations.AddField(
            model_name='profesor',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
